### ISSUE TITLE
Can somebody teach me how to hack?!

### ISSUE THREAD

**Issue by ZoroKissama** [Pure-L0G1C/Instagram#26]
i want to learn how to hack Instagram/Google/Facebook account! Did i come to the right place?!

**Comment by Ethical-H4CK3R** [comment]
I can teach you how to program, but not how to hack. If you’re talking
about real hacking and not script kiddie hacking, then it’s a skill that is
developed through programming.

**Comment by ZoroKissama** [comment]
well, can u hack certain account for me please?

2018-02-22 23:07 GMT+01:00 Mohamed <notifications@github.com>:

**Comment by Ethical-H4CK3R** [comment]
Hacking is not cool if you're doing it illegally, you can end up in jail. If you're going to hack, hack only when the person gives the permission, other than that just hack yourself.

**Comment by ZoroKissama** [comment]
well i know that "Akhi" all i want is learn how to hack it's not like i'm
going to hack an agency or something, just random account and it's not like
i'm going to sell these accounts or something
 ... x)

2018-02-22 23:31 GMT+01:00 Mohamed <notifications@github.com>:

**Comment by Tosible** [comment]
@ZoroKissama Learn how to code lmao. Ethical-H4CK3R is not your personal army

**Comment by ZoroKissama** [comment]
How can i start


2018-02-25 8:51 GMT+01:00 Defalt <notifications@github.com>:

**Comment by Tosible** [comment]
> How can i start
Google, SoloLearn, Codeacademy, etc.

**Comment by Ethical-H4CK3R** [comment]
I recommend watching videos on sites like YouTube/Udemy, then writing a simple program that uses something you’ve learned from the video. Don’t do videos that says things like learn something in an hour or long videos, those never work. Instead watch videos that are broken into few minutes because the human can stay focused for more than ten minutes. Don’t do sites Codeacademy and Sololearn, they don’t work. When you start learning to are your own code start simple, don’t try to do something advanced or intermediate when you’re a beginner. Don’t do front end dev, it’s going to get extremely boring extremely fast, just do back end for now. And Finally never pay to learn to code; the payed content producers try too hard to make their content perfect and it becomes like normal school  - a failure. Free content producers teach better because they communicate with the student as a friend instead of a moron. Good luck, and  tell me every time you create a program, I want to see it.
