### ISSUE TITLE
I'm having some issues figuring out how this thing is structured

### ISSUE THREAD

**Issue by 61SjCabv7Z** [Pure-L0G1C/Instagram#51]
How is your code structured? Why do you have to go as deep as /lib/src/lib/ sometimes for some files?
Don't get me wrong the code works perfectly fine, but why do you need 20 python files for it?
I would really appreciate if you could explain why there are so many files and why some are even empty. It would really help for those who might want to develop what you've done.

**Comment by Pure-L0G1C** [comment]
I just separated my code into individual files instead of keeping everything one file, that makes it easier to fix bugs. Just like how each function does one thing, files are the same, each file does one thing. Later when an issue occurs I will know which file to look in. When you say empty files you must be referring to the files "init.py" those are required by Python, Python will treat a directory like a package when it sees those files in a directory.
