### ISSUE TITLE
Why make Queue a whole class when it's just an array?

### ISSUE THREAD

**Issue by 61SjCabv7Z** [Pure-L0G1C/Instagram#52]
Seriously this messed me up when I was trying to understand what you're doing. You recreated an array with the Queue class which is completely useless.

**Comment by Pure-L0G1C** [comment]
Haha, I feel like we should be communicating over something like Discord instead of through Github. I wrote it because I wanted the uniqueness in the array. I know it's slower than the Queue library, but my queue will make sure an item instead already included in the list. This will come in useful when scraping proxies and when reading a word list. Sometimes the same proxy might be repeated in a proxy website, and sometimes the same password might be repeated in a session. That will cause data redundancy for the password and waste of time for the proxy. So, by having a queue class I am able to create uniqueness.

**Comment by Pure-L0G1C** [comment]
I am unable to join your server. You have about 250 member already

**Comment by 61SjCabv7Z** [comment]
Just message me then, I'm Hedwig#0208
